# Generated by Django 4.1.3 on 2022-11-09 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('is_active', models.BooleanField(default=True, verbose_name='State')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Profesor')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo Profesor')),
                ('telefono', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ingresarse en el formato: 3004445566', regex='\\d{9,15}$')], verbose_name='Telefono Profesor')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
