# Generated by Django 4.1.3 on 2022-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('is_active', models.BooleanField(default=True, verbose_name='State')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre Asignatura')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Codigo Asignatura')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
