# Generated by Django 4.1.3 on 2022-11-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Asignatura'),
        ),
    ]
