# Generated by Django 4.1.3 on 2022-11-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('is_active', models.BooleanField(default=True, verbose_name='State')),
                ('salon', models.CharField(max_length=255, verbose_name='Salon Clase')),
                ('Horario', models.TimeField(verbose_name='Horario clase')),
                ('asignatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='asignatura.asignatura')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to='profesor.profesor')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
