# Generated by Django 4.1.3 on 2022-11-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
        ('asignatura', '0002_alter_asignatura_nombre'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='asignatura.asignatura'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to='profesor.profesor'),
        ),
    ]
